### ISSUE TITLE
DatabaseGenerator.winx64 doesn't have Script/Dataset folder 

### ISSUE THREAD

**Issue by SharmaAntriksh** [sql-bi/Contoso-Data-Generator-V2#1]
In docs you have mentioned Scripts/Dataset but when I downloaded the _**DatabaseGenerator.winx64**_ file it only has 4 files - Config, data, DatabaseGenerator, readme. There is no Script/Dataset folder

And the DatabaseGenerator is application file but it doesn't executes?

![image](https://github.com/user-attachments/assets/0ec16d92-64f2-4102-b627-2fed400dfd3e)

**Comment by marcosqlbi** [comment]
DatabaseGenerator is a command-line tool - you must run it from a command prompt.
I'm not sure we want to include all the scripts that are already part of the source code - they are not required unless you want to automate the generation of multiple databases.
@fhtino what do you think?
@SharmaAntriksh you can find all the scripts by downloading the whole project, not just the executable.

**Comment by fhtino** [comment]
@SharmaAntriksh  To run Contoso DatabaseGenerator, open a command prompt and execute:
`DatabaseGenerator.exe  config.json  data.xlsx  outfolder  cachefolder`
All required file (a single exe, a config example and data.xlsx) are in the zip.

We didn't include all the scripts in the distribution zip because they need precise position and have files/folders dependencies. They are designed to run if you GIT  CLONE  the whole repository.  And, even in that case, some of them requires some adaptation based on your need / environment  (e.g. sqlserver and database name).

**Comment by SharmaAntriksh** [comment]
@fhtino Thanks, I was able to use it with command line, and I also tried to convert CSV files into SQL and that worked but it only generates MDF and LDF can it also generate BAK file?

**Comment by marcosqlbi** [comment]
You can adapt this part of the SQLBI_ALL_DB.cmd to generate the backup file (the complete script is what we used to generate the files ready to download).

https://github.com/sql-bi/Contoso-Data-Generator-V2/blob/2c65f6ac8164d72b4f67e9fea1523fb19dffd515/scripts/sql/SQLBI_ALL_DB.cmd#L53C1-L57C57

**Comment by SharmaAntriksh** [comment]
Thanks, couldn't make it work so I relied on PS for short and simple command

Backup-SqlDatabase -ServerInstance "Demo" -Database "Contoso 100M"
