### ISSUE TITLE
Sales view not available when 'Orders' is specified

### ISSUE THREAD

**Issue by SharmaAntriksh** [sql-bi/Contoso-Data-Generator-V2#2]
I generated the CSV files using Orders parameters and it worked fine, but when I loaded the CSV into SQL using Sql_ImportData it didn't create the sales view, is this expected behaviour and we have to create the sales view? I think following sales view for Orders option can be useful when sales table isn't needed and we don't have to generate the view every time for each database.

```
SELECT 
        Orders.OrderKey AS [Order Number],
        OrderRows.[LineNumber] AS [Line Number],
        Orders.[OrderDate],
        Orders.[DeliveryDate],
        Orders.CustomerKey,
        Orders.StoreKey,
        OrderRows.ProductKey,
        OrderRows.Quantity,
        OrderRows.[UnitPrice],
        OrderRows.[NetPrice],
        OrderRows.[UnitCost],
        Orders.[CurrencyCode],
        [CurrencyExchange].Exchange AS [Exchange Rate]
    FROM
        [Data].Orders  
            LEFT OUTER JOIN [Data].OrderRows
                ON Orders.OrderKey = OrderRows.OrderKey
            LEFT OUTER JOIN [Data].[CurrencyExchange]
                ON 
                    [CurrencyExchange].Date = Orders.[OrderDate] AND
                    [CurrencyExchange].[ToCurrency] = Orders.[CurrencyCode] AND
                    [CurrencyExchange].[FromCurrency] = 'USD'
```

**Comment by marcosqlbi** [comment]
If you want to add the view, it's fine - this is the approach we used in v1.
In v2, we have a Sales table, which you can import, as well as Orders / OrderRows. The reason why we kept both is for educational purposes because depending on the condition, you want to use one or the other. Having both provides more flexibility. The reason why we didn't use the view is to support columnstore indexes for Sales in SQL Server.
